In [8]:
import pandas as pd
file_path = "../data_analysis_reports/data.xlsx"
data = pd.read_excel(file_path)

In [9]:
data

,Year,Month,InsuredCount,ChildLessThan18,AdultLessThan40,MiddleLessThan55,OldGreaterThan55,ActiveWeight_P1,ActiveWeight_P3,ActiveWeight_P4,...,ActiveWeight_P19,ActiveWeight_P21,Payment Amount,Male,Others,Female,Married,Unmarried,Acute,Chronic
0,0,January,136626,26040,90977,26300,2606,2533789,508722,398965,...,575602,342686,44852164,114879,1614,20133,118169,18457,38172,98454
1,0,February,125493,27393,85442,25467,2706,2448114,541483,420418,...,558697,353603,44659416,99331,452,25710,94881,30612,5678,119815
2,0,March,142683,26730,85344,27137,2428,2492737,562427,474710,...,577525,393263,44063816,114315,763,27605,125213,17470,32184,110499
3,0,April,128047,24259,78568,24174,2239,2421053,461990,437503,...,514085,308989,45525904,111318,1592,15137,106293,21754,7343,120704
4,0,May,107337,22638,71614,16728,1371,1992105,377978,253249,...,194745,257899,33637268,102078,1253,4006,70292,37045,15070,92267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,2023,November,143177,25757,92062,26710,2621,2575971,508170,397729,...,602138,341106,45234244,107002,1786,34389,121856,21321,5351,137826
995,2023,December,146122,26977,88671,27474,2571,2555805,567541,466263,...,617165,392132,44554212,138017,1790,6315,90310,55812,156,145966
996,2024,January,134676,24894,81833,24336,2348,2457246,465105,393970,...,525833,305197,44627024,71391,2301,60984,116623,18053,9754,124922
997,2024,February,147500,25413,90848,26615,2673,2581242,501029,402536,...,618412,337486,45918568,137659,1304,8537,77747,69753,15786,131714
998,2024,March,136565,28681,86749,26093,2927,2602472,563558,442841,...,644264,369569,45243720,99516,136,36913,118222,18343,59628,76937

In [14]:
from sklearn.preprocessing import StandardScaler
import pickle

X = data.drop(columns=['Month','Year','Payment Amount'])
y = data["Payment Amount"]

# Initialize and fit the scaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_scaled, y)

# Save the model and the scaler
with open('lm.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)

with open('scaler.pkl', 'wb') as scaler_file:
    pickle.dump(scaler, scaler_file)

In [15]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

# Splitting the data into features (X) and target (y)
X = data.drop(columns=['Month', 'Year', 'Payment Amount'])  # Adjust the column names if necessary
y = data['Payment Amount']

# Standardizing the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Fitting a linear regression model
model = LinearRegression()
model.fit(X_scaled, y)

# Getting the coefficients of the model
coefficients = model.coef_
feature_names = X.columns

# Creating a DataFrame to display the relation with the payment amount
relation_df = pd.DataFrame({
    'Field Name': feature_names,
    'Relation with Payment (%)': np.abs(coefficients) / np.sum(np.abs(coefficients)) * 100
})

# Sorting the DataFrame by the relation with payment
relation_df_sorted = relation_df.sort_values(by='Relation with Payment (%)', ascending=False)

# Display the sorted DataFrame
print(relation_df_sorted)

          Field Name  Relation with Payment (%)
0       InsuredCount               2.328271e+01
27           Married               1.364910e+01
24              Male               1.324041e+01
30           Chronic               1.318199e+01
29             Acute               1.232018e+01
26            Female               1.192770e+01
28         Unmarried               1.192279e+01
25            Others               4.751339e-01
15  ActiveWeight_P12               3.733178e-10
14  ActiveWeight_P11               2.109826e-10
7    ActiveWeight_P4               2.091693e-10
3   MiddleLessThan55               1.522927e-10
19  ActiveWeight_P16               1.336788e-10
5    ActiveWeight_P1               1.329820e-10
22  ActiveWeight_P19               1.255258e-10
23  ActiveWeight_P21               1.228853e-10
6    ActiveWeight_P3               1.038921e-10
2    AdultLessThan40               7.911000e-11
8    ActiveWeight_P5               7.133206e-11
10   ActiveWeight_P7               7.112487e-11
1    ChildLessThan18               6.464592e-11
11   ActiveWeight_P8               5.186106e-11
4   OldGreaterThan55               5.115195e-11
21  ActiveWeight_P18               4.386284e-11
20  ActiveWeight_P17               2.582519e-11
16  ActiveWeight_P13               2.191005e-11
9    ActiveWeight_P6               9.095729e-12
18  ActiveWeight_P15               7.804929e-12
13  ActiveWeight_P10               1.155400e-12
17  ActiveWeight_P14               2.738679e-13
12   ActiveWeight_P9               3.681571e-14

In [16]:
relation_df_sorted.shape

(31, 2)

In [17]:
import pandas as pd

# Drop the 'Month' and 'Year' columns as they are not needed for correlation calculation
data_numeric = data.drop(columns=['Month', 'Year'])

# Calculating the correlation matrix
correlation_matrix = data_numeric.corr()

# Extracting the correlation of each field with the 'Payment Amount'
payment_correlation = correlation_matrix['Payment Amount'].drop('Payment Amount')

# Creating a DataFrame to display the correlation with the payment amount
correlation_df = pd.DataFrame({
    'Field Name': payment_correlation.index,
    'Correlation with Payment Amount': payment_correlation.values
})

# Sorting the DataFrame by the correlation with payment amount
correlation_df_sorted = correlation_df.sort_values(by='Correlation with Payment Amount', ascending=False)

# Display the sorted DataFrame
print(correlation_df_sorted)

          Field Name  Correlation with Payment Amount
22  ActiveWeight_P19                         0.934677
13  ActiveWeight_P10                         0.934183
3   MiddleLessThan55                         0.934173
5    ActiveWeight_P1                         0.926426
7    ActiveWeight_P4                         0.904083
11   ActiveWeight_P8                         0.887307
4   OldGreaterThan55                         0.879543
8    ActiveWeight_P5                         0.871358
0       InsuredCount                         0.843878
9    ActiveWeight_P6                         0.814485
18  ActiveWeight_P15                         0.806327
16  ActiveWeight_P13                         0.802689
20  ActiveWeight_P17                         0.798033
19  ActiveWeight_P16                         0.783916
15  ActiveWeight_P12                         0.766594
10   ActiveWeight_P7                         0.764762
6    ActiveWeight_P3                         0.747059
23  ActiveWeight_P21                         0.746824
2    AdultLessThan40                         0.690464
21  ActiveWeight_P18                         0.614178
1    ChildLessThan18                         0.585846
14  ActiveWeight_P11                         0.585099
27           Married                         0.394886
24              Male                         0.376561
30           Chronic                         0.333301
29             Acute                         0.177624
26            Female                         0.116207
25            Others                         0.112383
28         Unmarried                         0.104900
17  ActiveWeight_P14                        -0.788481
12   ActiveWeight_P9                              NaN

In [18]:
import pandas as pd

data_numeric = data.drop(columns=['Month', 'Year'])

# Calculating the correlation matrix
correlation_matrix = data_numeric.corr()

# Extracting the correlation of each field with the 'Payment Amount'
payment_correlation = correlation_matrix['Payment Amount'].drop('Payment Amount')

# Creating a dictionary to store the correlations
correlation_dict = payment_correlation.to_dict()

# Defining the object with each field as a property
class CorrelationWithPayment:
    def __init__(self, correlations):
        for field, value in correlations.items():
            setattr(self, field, value)

# Creating an instance of the object
correlation_object = CorrelationWithPayment(correlation_dict)

# Printing the properties of the object
for field in correlation_dict.keys():
    print(f'{field}: {getattr(correlation_object, field)}')

InsuredCount: 0.8438780103545538
ChildLessThan18: 0.5858460154927358
AdultLessThan40: 0.6904640018059682
MiddleLessThan55: 0.9341732159789795
OldGreaterThan55: 0.8795431092459868
ActiveWeight_P1: 0.9264258741206493
ActiveWeight_P3: 0.7470590928626717
ActiveWeight_P4: 0.9040831565604383
ActiveWeight_P5: 0.8713578707190931
ActiveWeight_P6: 0.8144853249263238
ActiveWeight_P7: 0.7647619165529909
ActiveWeight_P8: 0.8873072792726958
ActiveWeight_P9: nan
ActiveWeight_P10: 0.9341831919570242
ActiveWeight_P11: 0.5850994646002138
ActiveWeight_P12: 0.7665935764465123
ActiveWeight_P13: 0.8026885807022159
ActiveWeight_P14: -0.7884810964833439
ActiveWeight_P15: 0.8063267875705231
ActiveWeight_P16: 0.783916186599304
ActiveWeight_P17: 0.7980334449159426
ActiveWeight_P18: 0.614178273812169
ActiveWeight_P19: 0.9346767146277427
ActiveWeight_P21: 0.7468240412334572
Male: 0.3765605558428566
Others: 0.11238322987127575
Female: 0.11620684642083706
Married: 0.39488611614723557
Unmarried: 0.10490039103994225
Acute: 0.1776244404637258
Chronic: 0.3333005974723666